### ISSUE TITLE
Не зачту проект, пока вы не исправите security alerts

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2019-4-chat#12]

**Comment by Mazdaywik** [comment]
Исправлено в<span>&nbsp;</span>#11.

**Comment by Mazdaywik** [comment]
Они опять вылезли после #13.

**Comment by Mazdaywik** [comment]
`npm audit fix` прекрасно исправляет все три предупреждения.

**Comment by Mazdaywik** [comment]
Но я не буду коммитить исправления. Сами запускайте `npm audit fix`, проверяйте, что после автоматического исправления ничего не сломалось и коммитьте.

**Comment by NikitaLobaev** [comment]
Исправил прошлые предупреждения.

**Comment by Mazdaywik** [comment]
Текущие три никуда не делись: https://github.com/bmstu-iu9/utp2019-4-chat/network/alerts

**Comment by Mazdaywik** [comment]
`npm audit fix` их исправляет.

**Comment by Mazdaywik** [comment]
Исправлено в<span>&nbsp;</span>#15.
